name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ x64, x86 ]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{ env.SOLUTION_FILE_PATH }}

    - name: Setup VSTest and add to PATH
      uses: darenm/Setup-VSTest@v1

    - name: Run VSTest
      run: vstest.console.exe /Platform:${{ matrix.platform }} /Enablecodecoverage .\\${{ matrix.platform }}\\${{ matrix.configuration }}\\test.dll